apiVersion: loki.grafana.com/v1
kind: LokiStack
metadata:
  name: logging
  namespace: loki-stack
spec:
  size: 1x.small
  storage:
    schemas:
    - version: v13
      effectiveDate: "2024-01-01"
    secret:
      name: loki-bucket-claim
      type: s3
  storageClassName: ocs-storagecluster-ceph-rbd
  tenants:
    mode: openshift-logging
