apiVersion: objectbucket.io/v1alpha1
kind: ObjectBucketClaim
metadata:
  name: loki-bucket-claim
  namespace: loki-stack
spec:
  generateBucketName: loki-logs
  storageClassName: openshift-storage.noobaa.io
