{
 "title": "Loki: Application Logs",
 "tags": [
  "loki",
  "openshift",
  "apps"
 ],
 "templating": {
  "list": [
   {
    "name": "namespace",
    "query": "label_values({tenant=\"application\"}, namespace)"
   }
  ]
 },
 "panels": [
  {
   "title": "Log Volume by Namespace",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "sum by (namespace) (count_over_time({tenant=\"application\"} [$__interval]))",
     "legendFormat": "{{namespace}}"
    }
   ]
  },
  {
   "title": "Error Rate (keywords: error, fail, exception)",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "sum(count_over_time({tenant=\"application\"} |~ \"(?i)error|fail|exception\" [$__interval]))"
    }
   ]
  },
  {
   "title": "Log Streams",
   "type": "logs",
   "gridPos": { "h": 16, "w": 24, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "{tenant=\"application\"} | json"
    }
   ]
  }
 ]
}