apiVersion: grafana.integreatly.org/v1beta1
kind: GrafanaDatasource
metadata:
  name: loki-application
  namespace: grafana
spec:
  instanceSelector:
    matchLabels:
      dashboards: "grafana" # Upewnij się, że Twoja instancja Grafany ma ten label
  datasource:
    name: "Loki (Applications)"
    type: loki
    url: "http://logging-loki-gateway-http.loki-stack.svc:8080"
    jsonData:
      httpHeaderName1: "X-Scope-OrgID"
    secureJsonData:
      httpHeaderValue1: "application"
---
apiVersion: grafana.integreatly.org/v1beta1
kind: GrafanaDatasource
metadata:
  name: loki-network
  namespace: grafana
spec:
  instanceSelector:
    matchLabels:
      dashboards: "grafana"
  datasource:
    name: "Loki (Network)"
    type: loki
    url: "http://logging-loki-gateway-http.loki-stack.svc:8080"
    jsonData:
      httpHeaderName1: "X-Scope-OrgID"
    secureJsonData:
      httpHeaderValue1: "network"
