apiVersion: grafana.integreatly.org/v1beta1
kind: GrafanaDatasource
metadata:
  name: loki-application
  namespace: grafana
spec:
  instanceSelector:
    matchLabels:
      dashboards: "grafana"
  datasource:
    name: "Loki-Apps-mTLS" # Zmieniona nazwa, aby uniknąć konfliktu
    type: loki
    url: "https://logging-gateway-http.loki-stack.svc:8080"
    access: proxy
    jsonData:
      tlsAuth: true
      tlsAuthWithCACert: true
      tlsSkipVerify: false
      httpHeaderName1: "X-Scope-OrgID"
      httpHeaderName2: "Authorization"
    secureJsonData:
      tlsCACert: "PLACEHOLDER_CA"
      tlsClientCert: "PLACEHOLDER_CLIENT_CERT"
      tlsClientKey: "PLACEHOLDER_CLIENT_KEY"
      httpHeaderValue1: "application"
      httpHeaderValue2: "Bearer PLACEHOLDER_TOKEN"
